brand:
  name: SardonX Global
menu-string: Menu

nav:
  - title: Missions
    url: '#missions'
  - title: Products
    url: '#products'
  - title: How to
    url: '#about'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; SardonX Global 2020

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  supply-string: 'Capacity: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Product'
